### ISSUE TITLE
kinda sus ngl

### ISSUE THREAD

**Issue by bruhsussy** [MushyToast/schooltest#1]
I think it might work on chromebooks but my school uses lightspeed agent so yeah
for me when i use google (on my phone), depending on if it has like a cuss word or something it gives me a not allowed screen
my block screen looks like this how bout yours

also what does ur school use to block stuff

**Comment by MushyToast** [comment]
you just posted your ip address and your school district, it doesnt get blocked for me, why does it get blocked on your phone?

**Comment by bruhsussy** [comment]
lmao I dont care about the ip this is my school computer but ill remove it

**Comment by bruhsussy** [comment]
So that block screen that I showed you was the block schrren for my school computer.

**Comment by bruhsussy** [comment]
not for my phone

**Comment by bruhsussy** [comment]
I think there is someone at the school who manages the lightspeed filtering

**Comment by bruhsussy** [comment]
me personally i have a dell not a chromebook for school

**Comment by bruhsussy** [comment]
but ye as far as on my PHONE and not my computer, my phone blocks stuff due to keywords.

**Comment by bruhsussy** [comment]
also i invited u to a github group so join it

**Comment by MushyToast** [comment]
ok, il close this (i joined the group)
